spring:
  datasource:
    url: jdbc:mysql://10.81.44.187:3306/watcher?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 10.81.44.187
    db: 1
    password: 123456

server:
  port: 8112

cas:
   client:
     host: http://127.0.0.1:8112
