spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/watcher?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    min-idle: 5
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 11
  cache:
    type: redis
    redis:
      time-to-live: 2h

cas:
  server:
    host: http://sso.ob.aihuishou.com:8080/casservice
    login: http://sso.ob.aihuishou.com:8080/casservice/login
    logout: http://sso.ob.aihuishou.com:8080/casservice/logout?service=http://10.25.169.133:8080
  client:
    host: http://10.25.169.133:8080

proxy:
    watcher:
        servlet_url: /watcher/*
        target_url: http://watcher.intra.aihuishou.com:8809/watcher
        logging_enabled: true