spring:
  datasource:
    url: jdbc:mysql://10.81.44.187:3306/watcher?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 10.81.44.187
    password: 123456
    database: 1

server:
  port: 8080

cas:
   client:
     host: http://10.25.169.133:8080
